Feat/init password vault
ClassiVault/ClassiVault.Api pull request #3
Opened 2023-11-17 18:26 UTC by AbdulmajeedAlOmari

FYR @AhmedAlzubaidi

2023-11-18 19:17 UTC, AhmedAlzubaidi requested changes

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on Controllers/EncryptionKeyInfoController.cs
> +public class EncryptionKeyInfoController : ControllerBase
the route of this controller is /encryptionkeyinfo ?
if so can't we make it shorter

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on Controllers/PasswordVaultController.cs
> +[Route("api/[controller]")]
hmmm /vaults ? instead

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on DataAccess/AppDbContext.cs
> +            modelBuilder.Entity<EncryptionKeyInfo>().HasKey(eki => eki.KeyID);
here is what I suggest
- the primary key seems unpredictable change it to id
- all database keys lowercase
- underscore separated

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on DataAccess/Models/EncryptionKeyInfo.cs
> +  public class EncryptionKeyInfo
maybe shorten it to EncryptionKey

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on DataAccess/Models/EncryptionKeyInfo.cs
> +      public DateTime UpdatedAt { get; set; }
I suggest we make a base model that contains CreatedAt and UpdatedAt
```c#
 public abstract class BaseEntity
 {
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
 }
 
 public class EncryptionKeyInfo : BaseEntity
```

2023-11-18 19:17 UTC, AhmedAlzubaidi commented on DataAccess/Models/PasswordVault.cs
> +  public class PasswordVault
I suggest we change this to Vault or ClassiVault 😄, because we might store other things that are not passwords

2023-11-18 22:35 UTC, AbdulmajeedAlOmari commented on Controllers/EncryptionKeyInfoController.cs
> +public class EncryptionKeyInfoController : ControllerBase
Done

2023-11-18 22:35 UTC, AbdulmajeedAlOmari commented on Controllers/PasswordVaultController.cs
> +[Route("api/[controller]")]
Done

2023-11-18 22:39 UTC, AbdulmajeedAlOmari commented on DataAccess/AppDbContext.cs
> +            modelBuilder.Entity<EncryptionKeyInfo>().HasKey(eki => eki.KeyID);
This is best practice naming convention for .NET apps, we can leave it as it is

Also, for primary keys,  we could go for both ways

Either rename all PKs to Id, or keep it as it is for better differentiation in queries later on

2023-11-18 22:39 UTC, AbdulmajeedAlOmari commented on DataAccess/Models/EncryptionKeyInfo.cs
> +  public class EncryptionKeyInfo
Done

2023-11-18 22:51 UTC, AbdulmajeedAlOmari commented on DataAccess/Models/EncryptionKeyInfo.cs
> +      public DateTime UpdatedAt { get; set; }
Done

2023-11-18 22:51 UTC, AbdulmajeedAlOmari commented on DataAccess/Models/PasswordVault.cs
> +  public class PasswordVault
Done

2023-11-18 22:51 UTC, AbdulmajeedAlOmari commented on DataAccess/AppDbContext.cs
> +            modelBuilder.Entity<EncryptionKeyInfo>().HasKey(eki => eki.KeyID);
Done

2023-11-19 17:30 UTC, AhmedAlzubaidi approved these changes

2023-11-19 17:31 UTC, merged